# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# always refer to Hyprland wiki
# https://wiki.hyprland.org/

# Initial boot script enable to apply initial wallpapers, theming, new settings etc.
# suggest not to change this or delete this including deleting referrence file in ~/.config/hypr/.initial_startup_done
# as long as the referrence file is present, this initial-boot.sh will not execute
exec-once = $HOME/.config/hypr/initial-boot.sh

# Sourcing external config files
$configs = $HOME/.config/hypr/configs # Default Configs directory path

source=$configs/Keybinds.conf # Pre-configured keybinds

# ## This is where you want to start tinkering 
$UserConfigs = $HOME/.config/hypr/UserConfigs # User Configs directory path

source= $UserConfigs/Startup_Apps.conf # put your start-up packages on this file

source= $UserConfigs/ENVariables.conf # Environment variables to load

#source= $UserConfigs/Monitors.conf # Its all about your monitor config (old dots) will remove on push to main
#source= $UserConfigs/WorkspaceRules.conf # Hyprland workspaces (old dots) will remove on push to main

source= $UserConfigs/Laptops.conf # For laptop related

source= $UserConfigs/LaptopDisplay.conf # Laptop display related. You need to read the comment on this file

source= $UserConfigs/WindowRules.conf # all about Hyprland Window Rules and Layer Rules

source= $UserConfigs/UserDecorations.conf # Decorations config file
source= ~/.cache/wal/colors-hyprland.conf

source= $UserConfigs/UserAnimations.conf # Animation config file

source= $UserConfigs/UserKeybinds.conf # Put your own keybinds here

source= $UserConfigs/UserSettings.conf # Main Hyprland Settings.

source= $UserConfigs/01-UserDefaults.conf # settings for User defaults apps

# nwg-displays
source= $HOME/.config/hypr/monitors.conf
source= $HOME/.config/hypr/workspaces.conf

plugin:dynamic-cursors {
    enabled = true
#    mode = stretch
}

plugin {
    hyprtrails {
        color = rgba(00ff88ff)
    }
}

plugin {
    hyprexpo {
        columns = 3
        gap_size = 5
        bg_col = rgb(111111)
        workspace_method = center current # [center/first] [workspace] e.g. first 1 or center m+1

        gesture_distance = 300 # how far is the "max" for the gesture
    }
}

plugin {
    hyprwinwrap {
        # class is an EXACT match and NOT a regex!
        class = kitty-bg
        # you can also use title
        title = kitty-bg
        # you can add the position of the window in a percentage
        pos_x = 45
        pos_y = 45
        # you can add the size of the window in a percentage
        size_x = 50
        size_y = 50
    }
}
