# 1. 執行標準的啟動項目 (dex)
# dex 是一個工具，專門用來讀取系統中 /etc/xdg/autostart 裡的 .desktop 檔案。
# 功能：如果你安裝了一些軟體（例如 Dropbox、Discord 或輸入法），它們通常會註冊在 XDG 啟動目錄中。這一行確保這些軟體在進入 i3 時能像在一般桌面環境中一樣自動啟動。
exec dex --autostart --environment sway

# 自動鎖屏管理 (swaylock + swayidle)
# ==========================

# 按下 $mod+Ctrl+l 鎖屏
bindsym $mod+Ctrl+l exec swaylock -i /home/ar/Pictures/wallpaper.jpg

## 自動鎖屏 (swaylock + swayidle)
#exec swayidle -w \
#         timeout 30 'swaylock -i /home/ar/Pictures/wallpaper.jpg' \
#         timeout 60 'swaymsg "output * power off"' \
#         resume 'swaymsg "output * power on"' \
#         before-sleep 'swaylock -i /home/ar/Pictures/wallpaper.jpg'
