# tmp

# 向後切換視窗
bindsym Mod1+Tab focus next

# 確保環境變數同步：強迫 systemd 和 D-Bus 立即更新環境變數
#exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway SWAYSOCK
#exec systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# Sway 官方更建議使用更簡潔的語法，它會自動抓取當前已設定的所有變數並推送到 systemd
#exec hash dbus-update-activation-environment 2>/dev/null && \ dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP=sway

# 讓 systemd 和 D-Bus 知道 Wayland 的存在
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway

# 某些情況下需要這一行確保環境變數完整匯入
exec systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# ======
# DPI 設定
# ======
output HDMI-1 scale 1
output DP-1 scale 1

# ========
# XWayland
# ========

# 針對 XWayland 相容性： 若你仍有 X11 程式需運行，可在 Sway 設定檔加入：
# 確保 XWayland 啟動完成，再執行 xrdb -merge 

exec xrdb -merge "/home/ar/_dots/dotfiles/conf-xresources/xresources"
exec xrdb -merge "/home/ar/arch_file/dotfiles-ar/conf-xresources/colors-Tokyo"

# 解決 XWayland 關閉後失效的問題：強迫 XWayland 永遠保持開啟，不隨程式關閉而結束
xwayland force

# ========
# XWayland


# 3. 網路管理圖示 (nm-applet)
# ===========================
# nm-applet：這是 NetworkManager 的圖形化前端。
# 功能：執行後，你會在右下角的 系統匣（System Tray） 看到一個 Wi-Fi 或有線網路的圖示。你可以點擊它來切換網路、輸入密碼或查看連線狀態。
#exec nm-applet --indicator

# ============
# 通知守護進程
# ============

exec swaync

# 在 sway config 中設定 Super + N 開啟通知中心
bindsym $mod+n exec swaync-client -t -sw

# =========
# Wallpaper
# =========

# 替代 feh：swaybg + pywal

bindsym $mod+w exec sh -c 'img=$(find ~/Pictures/wallpapers -type f | shuf -n 1) && wal -i "$img" -n && swaymsg "output * bg $img fill" && swaync-client -rs'
