# fcitx 5
#exec fcitx5 -d
#exec fcitx5 --disable=statusnotifier,notification -d

# 禁用 fcitx5 系統托盤圖標
#exec env DBUS_SESSION_BUS_ADDRESS=none fcitx5 -d

#exec env DBUS_SESSION_BUS_ADDRESS=none fcitx5 --disable=statusnotifier,notification -d

exec fcitx5 --disable=notificationitem -d

# swaybg 30 分鐘自動更改桌布
#exec_always pkill -f "sway-wallpaper-loop"; exec_always --no-startup-id sh -c 'while true; do swaymsg "output * bg $(find ~/Pictures/wallpapers -type f | shuf -n 1) fill"; sleep 1800; done' &
exec sh -c 'while true; do img=$(find /home/ar/Pictures/wallpapers -type f | shuf -n 1); wal -i "$img" -n; swaymsg output "*" bg "$img" fill; swaync-client -rs; sleep 1800; done'

# """
# exec_always：確保每次重新載入 i3 (Mod+Shift+R) 時都會執行。
# while true; do ... done：這是一個 Bash 的無限迴圈。
# sleep 1800：暫停 1800 秒（即 30 分鐘）。
# """
