# Use pactl to adjust volume in PulseAudio.
# =========================================

# 1 .定義變數 $refresh_i3status
# 發送一個「信號 (SIGUSR1)」給 i3status。這會強制 i3status 立即重新整理（原本可能每 5 秒才更新一次），讓你在調整音量後，狀態列上的數字會立刻跳動。
#set $refresh_i3status killall -SIGUSR1 i3status
set $refresh_i3blocks pkill -RTMIN+10 i3blocks

# 2. 調高音量
# XF86AudioRaiseVolume：鍵盤上的「音量增加」鍵。
# pactl set-sink-volume @DEFAULT_SINK@ +10%：呼叫 PulseAudio 控制工具，將預設輸出裝置的音量調高 10%。
# && $refresh_i3status：音量調完後，執行前面定義的更新指令。
bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status

# 3. 調低音量
# XF86AudioLowerVolume：鍵盤上的「音量減少」鍵。
bindsym XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status

# 4. 喇叭靜音切換
# XF86AudioMute：鍵盤上的「靜音」鍵。
# set-sink-mute ... toggle：切換靜音狀態。是靜音就取消，反之亦然。
bindsym XF86AudioMute exec pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status

# 5. 麥克風靜音切換
# XF86AudioMicMute：鍵盤上的「麥克風靜音」鍵。
# set-source-mute：這裡針對的是 source（輸入裝置/麥克風），同樣是切換靜音狀態。
bindsym XF86AudioMicMute exec pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status

# exec --no-startup-id：這告訴 i3 在背景執行指令，且不要顯示啟動中的滑鼠沙漏圖示（因為這些指令執行速度極快，不需要視覺提示）。
# @DEFAULT_SINK@：自動指向目前的預設播放裝置（耳機或喇叭）。
