# 定義登出模式
set $mode_system Exit Sway? (y)yes / (n)cancel
mode "$mode_system" {
    bindsym y exec swaymsg exit
    bindsym n mode "default"
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

#set $mode_system (l)ock, (e)xit, switch_(u)ser, (s)uspend, (h)ibernate, (r)eboot, (Shift+s)hutdown
#mode "$mode_system" {
#    bindsym l exec i3lock, mode "default"
#    bindsym s exec systemctl suspend, mode "default"
#    bindsym e exec i3-msg exit, mode "default"
#    bindsym h exec systemctl hibernate, mode "default"
#    bindsym r exec systemctl reboot, mode "default"
#    bindsym Shift+s exec systemctl poweroff, mode "default"
#    
#    # exit system mode: "Enter" or "Escape"
#    bindsym Return mode "default"
#    bindsym Escape mode "default"
#}

