# terminal
bindsym $mod+Return exec st

#bindsym $mod+Return exec sh -c 'xrdb -query | grep -q "." || xrdb -merge ~/arch_file/dotfiles-ar/conf-xresources/colors-Tokyo; exec st'

bindsym $mod+b exec flatpak run com.brave.Browser   # exec / brave

# launcher-dmenu
bindsym $mod+d exec dmenu_run       # no-startup-id / dmenu

# launcher-rofi
# =============

# # 啟動剪貼簿監聽
exec wl-paste --watch cliphist store

# 合併顯示視窗與應用程式
set $spotlight ~/.config/rofi/spotlight.rasi
bindsym $mod+r exec "rofi -combi-modi window,run,drun,ssh -show combi -theme $spotlight -icon-theme 'Papirus' -show-icons"
# ctrl+tab toogle rofi mode

# 剪貼簿
bindsym $mod+c exec cliphist list | rofi -dmenu -p "Clipboard" -theme $spotlight | cliphist decode | wl-copy

# emoji
bindsym $mod+period exec "rofimoji --action copy --selector-args '-theme $spotlight'"
#bindsym $mod+period exec "rofimoji --action copy"

#rofi -show window -show-icons
#rofi -show drun -show-icons
#rofi -show window -show-icons
#rofi -show ssh

# screenshots
# ===========

# 1. 截圖選取區域，並存檔與複製。
bindsym $mod+shift+s exec exec sh -c 'mkdir -p ~/tmp/imgs && FILE="$HOME/tmp/imgs/$(date +'%Y-%m-%d-%H%M%S_screenshot.png')" && grimshot save area "$FILE" && wl-copy < "$FILE" && notify-send "截圖成功" "已儲存至 $FILE 並複製到剪貼簿" -i "$FILE"'

# 2. 只按 Print 截「當前螢幕」，並存檔與複製。(grimshot save output)
bindsym Print exec exec sh -c 'mkdir -p ~/tmp/imgs && FILE="$HOME/tmp/imgs/$(date +'%Y-%m-%d-%H%M%S_screenshot.png')" && grimshot save output "$FILE" && wl-copy < "$FILE" && notify-send "截圖成功" "已儲存至 $FILE 並複製到剪貼簿" -i "$FILE"'

## 3. 只按 Print 截「當前視窗」，並存檔與複製。(grimshot save output)
#bindsym Print exec exec sh -c 'mkdir -p ~/tmp/imgs && FILE="$HOME/tmp/imgs/$(date +'%Y-%m-%d-%H%M%S_screenshot.png')" && grimshot save active "$FILE" && wl-copy < "$FILE" && notify-send "截圖成功" "已儲存至 $FILE 並複製到剪貼簿" -i "$FILE"'

## 4. 截全螢幕（兩個螢幕同時），並存檔與複製。(grimshot save screnn)
#bindsym Print exec exec sh -c 'mkdir -p ~/tmp/imgs && FILE="$HOME/tmp/imgs/$(date +'%Y-%m-%d-%H%M%S_screenshot.png')" && grimshot save screen "$FILE" && wl-copy < "$FILE" && notify-send "截圖成功" "已儲存至 $FILE 並複製到剪貼簿" -i "$FILE"'
