# border toggle (title hidden)
# ============================

bindsym $mod+z border toggle

# bar mode toggle
# ===============

bindsym $mod+shift+m bar mode toggle

# reload / restart / exit
# =======================

# reload the configuration file
bindsym $mod+Shift+r reload

# exit i3 (logs you out of your X session)
#bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"
