#!/bin/sh

# Xresources files
xrdb -merge "/home/ar/_data/ar-dots/dotfiles/conf-xresources/xresources"
xrdb -merge "/home/ar/_data/ar-dots/dotfiles/conf-xresources/colors-Tokyo"

# 載入雙螢幕佈局 (DP-1 為主，HDMI-1 在左)
xrandr --output DP-1 --auto --left-of HDMI-1 --output HDMI-1 --primary --auto

# zsh
#source ~/.zprofile

# flatpak
exec dbus-launch --exit-with-session i3

# 啟動 wm
exec i3
#exec openbox-session
#sxhkd &
#exec bspwm
