foreground         #c7c5c2
background         #22190e
background_opacity 1.0
cursor             #c7c5c2

active_tab_foreground     #22190e
active_tab_background     #c7c5c2
inactive_tab_foreground   #c7c5c2
inactive_tab_background   #22190e

active_border_color   #c7c5c2
inactive_border_color #22190e
bell_border_color     #3f4844

color0       #22190e
color8       #72695e
color1       #3f4844
color9       #55615B
color2       #733c28
color10      #9A5036
color3       #7f3c2a
color11      #AA5039
color4       #774e3d
color12      #9F6952
color5       #546657
color13      #718875
color6       #93714b
color14      #C59764
color7       #9b9791
color15      #c7c5c2
