# 類型   路徑             權限  用戶  群組  存活時間  目標

# L type
# ======

# /etc/environment
L+    /etc/environment    -    -    -    -     /home/ar/_data/_dots/dotfiles/_tmpfiles/environment

# DNS：強制確保 /etc/resolv.conf 指向 stub 檔案
L+    /etc/resolv.conf    -    -    -    -    /run/systemd/resolve/stub-resolv.conf

# C type
# ======

# wifi
# 改用 C (Copy)，將 dotfiles 中的設定複製到 iwd 目錄，並強制設定權限
#C+     /var/lib/iwd/sowhat1124n.psk    0600    root    root    -    /home/ar/_data/_dots/dotfiles/_tmpfiles/sowhat1124n.psk
C+    /var/lib/iwd/sowhat1124mlo.psk    0600    root    root    -    /home/ar/_data/_dots/dotfiles/_tmpfiles/sowhat1124mlo.psk

# pacman mirrorlist
C+    /etc/pacman.d/mirrorlist    0644    root    root    -    /home/ar/_data/_dots/dotfiles/_tmpfiles/pacman_mirrorlist

# DNS file：/etc/systemd/resolved.conf
C+   /etc/systemd/resolved.conf    0644  root  root  -    /home/ar/_data/_dots/dotfiles/_tmpfiles/resolved.conf

# /etc/systemd/network/25-wireless.network
#C+     /etc/systemd/network/25-wireless.network  0644  systemd-network  systemd-network  -  /home/ar/_data/_dots/dotfiles/_tmpfiles/25-wireless.network
r    /etc/systemd/network/25-wireless.network  -    -    -    -    -
C    /etc/systemd/network/25-wireless.network  0644  systemd-network  systemd-network  -  /home/ar/_data/_dots/dotfiles/_tmpfiles/25-wireless.network

# /etc/vconsole.conf
r    /etc/vconsole.conf    -    -    -    -
C    /etc/vconsole.conf    -    -    -    -    /home/ar/_data/_dots/dotfiles/_tmpfiles/vconsole.conf

# /boot/loader/loader.conf
r /boot/loader/loader.conf
C /boot/loader/loader.conf 0644 root root - /home/ar/_data/_dots/dotfiles/_tmpfiles/loader.conf

# /etc/systemd/system/getty@tty1.service.d/autologin.conf
d      /etc/systemd/system/getty@tty1.service.d/                 0755  root  root  -     -
r     /etc/systemd/system/getty@tty1.service.d/autologin.conf
C     /etc/systemd/system/getty@tty1.service.d/autologin.conf    0644  root  root  -     /home/ar/_data/_dots/dotfiles/_tmpfiles/getty-autologin.conf
