# flatpak
# =======
# 1. 向 D-Bus 註冊桌面環境變數 (解決 Flatpak 啟動延遲與 Portal 辨識)
exec --no-startup-id dbus-update-activation-environment --systemd XDG_CURRENT_DESKTOP=i3

# 2. (選填) 如果你發現某些 GTK 軟體圖示異常，可補上這行
#exec --no-startup-id dbus-update-activation-environment --systemd DISPLAY XAUTHORITY

# 更新環境變數並啟動服務
exec --no-startup-id /usr/lib/xdg-desktop-portal &
#exec --no-startup-id "export XDG_CURRENT_DESKTOP=i3; dbus-update-activation-environment --systemd XDG_CURRENT_DESKTOP; systemctl --user start xdg-desktop-portal"

# fcitx 5
exec --no-startup-id fcitx5 -d

# feh
exec_always --no-startup-id while true; do feh --recursive --randomize --bg-fill ~/Pictures/wallpapers; sleep 1800; done

# """
# exec_always：確保每次重新載入 i3 (Mod+Shift+R) 時都會執行。
# while true; do ... done：這是一個 Bash 的無限迴圈。
# sleep 1800：暫停 1800 秒（即 30 分鐘）。
# """
