bindsym $mod+d exec --no-startup-id dmenu_run       # no-startup-id / dmenu
bindsym $mod+Return exec i3-sensible-terminal       # exec / terminal
bindsym $mod+b exec flatpak run com.brave.Browser   # exec / brave

# """
# A more modern dmenu replacement is rofi:
# bindcode $mod+40 exec "rofi -modi drun,run -show drun"
# There also is i3-dmenu-desktop which only displays applications shipping a
# .desktop file. It is a wrapper around dmenu, so you need that installed.
# bindcode $mod+40 exec --no-startup-id i3-dmenu-desktop
# """

# scrot
# =====
# 截圖選取區域並存檔至 ~/tmp/imgs，同時複製到剪貼簿
#bindsym $mod+shift+s exec --no-startup-id mkdir -p ~/tmp/imgs && scrot -s "$HOME/tmp/imgs/%Y-%m-%d-%H%M%S_screenshot.png" -e 'xclip -selection clipboard -t image/png -i $f'
bindsym $mod+shift+s exec --no-startup-id mkdir -p ~/tmp/imgs && scrot -s "$HOME/tmp/imgs/%Y-%m-%d-%H%M%S_screenshot.png" -e 'xclip -selection clipboard -t image/png -i $f && notify-send "截圖成功" "已儲存至 $f 並複製到剪貼簿" -i $f'

# 如果你想區分：只按 Print 截全螢幕，Mod+Print 截區域
bindsym Print exec --no-startup-id mkdir -p ~/tmp/imgs && scrot "$HOME/tmp/imgs/%Y-%m-%d-%H%M%S_screenshot.png" -e 'xclip -selection clipboard -t image/png -i $f && notify-send "截圖成功" "已儲存至 $f 並複製到剪貼簿" -i $f'

# feh
# =====
bindsym $mod+c exec --no-startup-id feh --recursive --randomize --bg-fill ~/Pictures/wallpapers

# """
# --recursive：包含子資料夾。
# --randomize：隨機挑選。
# --bg-fill：保持比例填滿桌面。
# """

# picom
# =====
bindsym $mod+p exec --no-startup-id pkill picom || picom -b

# """
# `pkill picom`：嘗試關閉名為 picom 的行程。
# `||`：這如果 pkill 失敗（代表 picom 本來就沒在執行），則執行後面的指令。
# picom -b：在背景啟動 picom。
# """
